DROP TABLE IF EXISTS photos;
CREATE TABLE photos(
    id INT PRIMARY KEY IDENTITY, 
    photo VARBINARY(MAX)
);

INSERT INTO photos SELECT * FROM OPENROWSET(BULK '/Users/behruz/Pictures/contract/IMG_20250411_224018_889.jpg', SINGLE_BLOB) AS IMG